# Generated by Django 6.0.2 on 2026-02-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='text', max_length=16)),
                ('ai_model', models.CharField(default='llama-3.1-8b-instant', max_length=64)),
                ('temperature', models.FloatField(default=0.2)),
                ('threshold', models.IntegerField(default=50)),
                ('has_pdf', models.BooleanField(default=False)),
                ('document_length', models.IntegerField(default=0)),
                ('result_json', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
